# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown
exclude: [_ignore]

plugins:
  - jekyll-extlinks
  - jekyll-feed
  - jekyll-scholar
  - jekyll-seo-tag
  - replace_regex

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tristan Bayfield
description: A site to showcase some of my work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tribayf.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty

# Contact
author: Tristan Bayfield
email: tristan&#x2e;bayfield&#064;sfu&#x2e;ca
github_username: tribayf
bitbucket_username: tribayf
twitter_username: tribayf

# Site settings
redirects: yes

collections:
  portfolio:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: portfolio-post

extlinks:
  attributes: { target: _blank }

scholar:
  style: ieee-with-url
  use_raw_bibtex_entry: true
  bibliography_template: bib
  bibliography_list_tag: table
  bibliography_item_tag: tr

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge

iis_slider_array: []

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
